FROM python:3.12-slim
WORKDIR /leclens

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend

ENV PYTHONPATH=/leclens

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "backend.app.run:app"]